PORT: localhost:3000

AUTH:
  USERNAME: username
  PASSWORD:

REDIS:
  HOST: localhost
  PORT: 6379

POSTGRE:
  DB_URL: "host=localhost user=postgres password= dbname=testovoe port=5432 sslmode=disable"